In [30]:
import torch

print(torch.__version__)

1.9.0+cpu


#### Get the current default floating point torch.dtype

In [31]:
torch.get_default_dtype()

torch.float64

#### default dtype for a tensor can only be a float type

In [32]:
torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

#### The default floating point dtype is initially torch.float32
#### Set the default floating point to torch.float64

In [ ]:
torch.set_default_dtype(torch.float64)

In [ ]:
torch.set_default_dtype(torch.float64)

In [ ]:
torch.get_default_dtype()

In [ ]:
torch.get_default_dtype()

#### Creating Tensors

#### A Tensor initialized with a specific array, the torch tensor always creates a copy of the data

In [ ]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

In [ ]:
arr= torch.tensor([[1,2],[3,4],[5,6]])
arr

In [ ]:
torch.is_tensor(arr)

In [ ]:
torch.is_tensor(tensor_arr)

#### numel() returns the number of elements in a tensor

In [ ]:
torch.numel(arr)

In [ ]:
torch.numel(tensor_arr)

#### An un-initialized Tensor of shape 2X2 allocated space in memory

In [ ]:
tensor_uninitialized = torch.Tensor(2, 2) 

In [33]:
a = torch.Tensor(3, 4) 

In [34]:
a

tensor([[2.3142e-306, 1.1126e-306, 1.0681e-306, 1.4242e-306],
        [1.1126e-306, 8.9009e-307, 1.8692e-306, 1.0681e-306],
        [1.3796e-306, 1.6911e-306, 1.7802e-306, 1.3796e-306]])

In [35]:
tensor_uninitialized

tensor([[0., 0.],
        [0., 0.]])

#### A tensor of size 2x2 initialized with random values

In [36]:
torch.rand(4,3)

tensor([[0.7080, 0.0201, 0.7836],
        [0.1529, 0.8260, 0.2371],
        [0.7795, 0.5724, 0.5085],
        [0.6131, 0.6521, 0.4702]])

In [37]:
tensor_initialized = torch.rand(2, 2)

In [38]:
tensor_initialized

tensor([[0.3825, 0.0060],
        [0.3702, 0.4092]])

#### Tensors can be set to have specific data types

In [39]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor) 
tensor_int

tensor([5, 3], dtype=torch.int32)

In [40]:
torch.rand(2,3).type(torch.IntTensor)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

#### A Tensor of type short

In [41]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])   
tensor_short

<ipython-input-41-cc07ff40659c>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

#### A Tensor of type float half (float16)

In [42]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

#### A tensor filled with a specific values


In [43]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [44]:
a = torch.ones([2,6])

In [45]:
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

#### A tensor of size (2,4) containing all ones

In [46]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [47]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### A tensor of size (2,4) like tensor_of_ones containing all zeroes

In [48]:
tensor_of_zeroes = torch.zeros_like(tensor_of_ones)
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [49]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### Create an identity 5X5 tensor

In [50]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [51]:
torch.nonzero(torch.eye(3,3))

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [52]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### Get the list of indices of non-zero elements in a tensor
[ i, j ] index for non-zero elements

In [53]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

#### Create a sparse tensor using coordinates specified by indices and values

In [54]:
i = torch.tensor([[0, 1, 1],
                  [2, 2, 0]])

In [55]:
i

tensor([[0, 1, 1],
        [2, 2, 0]])

In [56]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)
v

tensor([3., 4., 5.], dtype=torch.float32)

In [57]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [58]:
###########################

In [59]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

## Inplace / Out-of-place
The first difference is that ALL operations on the tensor that operate in-place on it will have an "\_" postfix. For example, add is the out-of-place version, and add\_ is the in-place version.

#### .fill_ is in-place operation and it doesnt have any out-place equivalent

In [65]:
initial_tensor = torch.rand(2, 3) 

initial_tensor

tensor([[0.6070, 0.0814, 0.2298],
        [0.2348, 0.1572, 0.9222]])

In [66]:
initial_tensor.fill_(10) 

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [67]:
initial_tensor.fill(10) 

AttributeError: 'Tensor' object has no attribute 'fill'

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [68]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

#### The original tensor is unchanged

In [69]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

#### The add\_ method does an in-place add, changing the calling tensor

In [70]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

#### The new_tensor was a separate copy and is unaffected

In [71]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

#### In-place version of sqrt()

In [72]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

### Indexing, Slicing, Joining, Mutating Ops

#### Slicing

In [78]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [79]:
t = torch.linspace(0.2,5,5)
t

tensor([0.2000, 1.4000, 2.6000, 3.8000, 5.0000])

#### Splits a tensor into a specific number of chunks.
- tensor (Tensor) – the tensor to split
- chunks (int) – number of chunks to return
- dim (int) – dimension along which to split the tensor


In [81]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [90]:
chunk = torch.chunk(x,2,-1)
chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500]),
 tensor([ 5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [92]:
chunk[1]

tensor([ 5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

#### Concatenates the  sequence of tensors along the given dimension

All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [93]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [94]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [95]:
random_tensor[0, 1]

tensor(8.)

In [96]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

#### Splits the tensor into chunks

In [97]:
random_tensor_split = torch.split(random_tensor, 2)
random_tensor_split

(tensor([[10.,  8., 30.],
         [40.,  5.,  6.]]),
 tensor([[12.,  2., 21.]]))

#### View

In [98]:
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [99]:
random_tensor.size()

torch.Size([3, 3])

In [100]:
resized_tensor = random_tensor.view(9)  
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [101]:
resized_tensor = random_tensor.view(-1, 6)  
resized_tensor

RuntimeError: shape '[-1, 6]' is invalid for input of size 9

In [ ]:
resized_tensor.size()

#### view() does not create a deep copy - just a view as the name suggests
Modifying the original tensor affects the resized_tensor as they both point to the same space in memory

In [103]:
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [123]:
rt = torch.rand(3,3)
rt

tensor([[0.2529, 0.5253, 0.0466],
        [0.0849, 0.8606, 0.8527],
        [0.8655, 0.0241, 0.4462]])

In [124]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

#### Unsqueeze
Returns a new tensor with a dimension of size one inserted at the specified position.

In [125]:
random_tensor[1,1]

tensor(5.)

In [127]:
random_tensor.shape

torch.Size([3, 3])

In [129]:
torch.unsqueeze(random_tensor, 1)

tensor([[[ 10.,   8.,  30.]],

        [[ 40.,   5.,   6.]],

        [[ 12.,   2., 100.]]])

In [139]:
tensor_unsqueeze = torch.unsqueeze(random_tensor,2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [140]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

#### Transpose

#### Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

In [141]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [142]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

#### Sorting tensors
Tensors can be sorted along a specified dimension. If no dimension is specified, the last dimension is picked by default

In [144]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [145]:
torch.sort(random_tensor)

torch.return_types.sort(
values=tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]]),
indices=tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]]))

In [146]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [147]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [148]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

# Math Operations
Pytorch supports a number of mathematical operations which can be performed on tensors. We take a look at a few of them here

In [149]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

#### Absolute values

In [150]:
tensor_abs = torch.abs(tensor_float)      
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [151]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [152]:
new_tensor = torch.add(initial_tensor, 2)
new_tensor

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [153]:
torch.add(initial_tensor, 10, new_tensor)

<ipython-input-153-c71eab5ef24a>:1: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:1025.)
  torch.add(initial_tensor, 10, new_tensor)


tensor([[218., 218., 218.],
        [218., 218., 218.]])

In [154]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [155]:
add1 = rand1 + rand2
add1

tensor([[0.7421, 1.1232, 1.1823],
        [2.0638, 2.0977, 0.6413]])

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [156]:
add2 = torch.add(rand1, rand2)
add2

tensor([[0.7421, 1.1232, 1.1823],
        [2.0638, 2.0977, 0.6413]])

In [157]:
tensor = torch.Tensor([[-1, -2, -3],
                       [ 1,  2,  3]])

#### Element-wise division
The div() and mul() functions can be used to divide and multiply the values in a tensor. Here, we do an element-wise division between two tensors

In [158]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

#### Element-wise multiplicaton

In [159]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

#### Clamp the value of a Tensor
There will be occasions where you would like to set upper and lower limits for the values in a tensor. This is where the clamp function is used. The value of an element is set to:
* min if if x<sub>i</sub> < min
* x<sub>i</sub> if min < x<sub>i</sub> < max
* max if x<sub>i</sub> > max

In [161]:
tensor_clamp = torch.clamp(tensor, min= -0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

## Vector Multiplication 

#### Dot product

In [162]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [163]:
dot_product = torch.dot(t1, t2) 
dot_product

tensor(50.)

#### Matrix Vector product
If mat is a (n×m) tensor, vec is a 1-D tensor of size m, out will be 1-D of size n.

In [164]:
matrix = torch.Tensor([[1, 2, 3],
                       [4, 5, 6]])

vector = torch.Tensor([0, 1, 2])

In [165]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

#### Matrix multiplication

In [166]:
another_matrix = torch.Tensor([[10, 30],
                               [20, 0],
                               [0 , 50]])

In [167]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

#### Returns the indices of the maximum values of a tensor across a dimension.

In [181]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [183]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])

In [169]:
torch.cuda.is_available()

False