In [1]:
import torch 

from torch.autograd import Variable

#### We create a Variable with Float tensor

The return value is not a variable instead it is a tensor

In [2]:
var = Variable(torch.FloatTensor([9]))
var

tensor([9.])

In [3]:
var.requires_grad

False

In [4]:
var.requires_grad_()

tensor([9.], requires_grad=True)

#### We create two weight variables with gradients enabled

In [5]:
w1 = Variable(torch.FloatTensor([3]), requires_grad = True)
w2 = Variable(torch.FloatTensor([7]), requires_grad = True)

In [6]:
w1

tensor([3.], requires_grad=True)

In [7]:
w2

tensor([7.], requires_grad=True)

#### We create two more variables using the weights

In [8]:
result_var = var * w1

result_var 

tensor([27.], grad_fn=<MulBackward0>)

#### New variables derive enabled gradients from weights

In [10]:
result_var.requires_grad

True

In [12]:
print(result_var.grad)

None


<ipython-input-12-1d1585c58e2b>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  print(result_var.grad)


In [13]:
result_var.backward()

In [14]:
w1.grad

tensor([9.])

In [16]:
w2.grad

In [17]:
var.grad

tensor([3.])